### PR TITLE
Various bugfixes

### PR DESCRIPTION
**Pull request by vanackej**
Here a few bugfixes, You can find the rational for each one in each commit.

### CODE REVIEW

**Comment by vanackej** [comment]
@TJForc I've also done an integration of your library with HomeAssistant using MQTT. Waiting for your approval on this to be able to publish it.

**Comment by pergolafabio** [comment]
Hi

where is that project ? is it the luca version ?

**Comment by pergolafabio** [comment]
@vanackej , do you mean this one? https://github.com/vanackej/risco-mqtt-home-assistant
isnt that still using the riscocloud api?

is it also possible to create an version without mqtt ? like the one now availble?

**Comment by vanackej** [comment]
@pergolafabio The branch where I replaced riscocloud API with LAN API is here : https://github.com/vanackej/risco-mqtt-home-assistant/tree/feature/lan_communication

For the discussion regarding MQTT integration, have a look at the comment here : https://github.com/lucacalcaterra/risco-mqtt-bridge/issues/42#issuecomment-955199906

For the version without MQTT, well, it's this project ! I just made some adjustements in this pull request to fix some bugs and improve some behaviors, but no big changes here.
I will maybe rewrite this project later using TypeScript and RxJS, because I'm more confortable with them and I think it could make maintenance and integration with third party libraries easier.

**Comment by pergolafabio** [comment]
Ah ok, sounds cool! So means we don't need an add-on? You gonna improve Onfreund his python version then?

**Comment by vanackej** [comment]
Don't need any addon on HA side, just using the standard https://www.home-assistant.io/integrations/alarm_control_panel.mqtt/ and https://www.home-assistant.io/integrations/binary_sensor.mqtt/ integrations to itnegrate the alarm panel and the sensors

**Comment by pergolafabio** [comment]
Perfect, but to run your project, it needs in a separate docker, right? Like Luca version?

**Comment by vanackej** [comment]
Yes, exactly. It will be the same, just based on the local API.
I don't want to migrate it to Python, as I'm not a good Python developer
and don't have time to do it.
I also think an external service integrated through MQTT is more likely to
get interest from various Home Automation communities : OpenHab, Jeedom, ...

Le sam. 30 oct. 2021 à 17:22, pergolafabio ***@***.***> a
écrit :

**Comment by pergolafabio** [comment]
Sounds good, can I contact you on discord?

**Comment by robertboccia** [comment]
We have been trying to get a risco solution in home assistant since the current integration broke when risco did an update a few months back so I hope this will solve the issues

Robert Boccia
________________________________

**Comment by TJForc** [comment]
first of all, good job

I have 2 small remarks:
- "Update internal state on Partitions before emitting events": you update the state of partitions and zones, I think we should also add for the outputs and the system to be more consistent.
- "Graceful disconnection ...": At this stage of the modifications, I do not see the need to add the export for the "RiscoPanel".
 @vanackej 
I think that this last point is related to the automatic detection of the type of plant but that it is not yet required at this stage.

Otherwise in principle, your modifications seem correct to me and go in the right direction of the project.

I await your return on these points before merging.

**Comment by TJForc** [comment]
@vanackej 
Regarding the MQTT project, I see no objection, quite the contrary.
This will avoid having to rewrite the code in python because like you, it is not a language that I master and I do not really have the time.
Remember to update the README on your project, it still refers to the REST API.

You should also know that I am working on adding the possibility of using the RS-232 (or USB in the case of the Prosys) connection of the control panels supporting it for a direct physical connection without going through the network, which would allow users without a network module (or not wishing to use proxy mode with an old IP module while retaining the connection to RiscoCloud) to be able to communicate with their control panel.
It will therefore be necessary to take into account this feature to come in your development.

When this is ready, the current project will be deprecated because I made the mistake of using the word 'lan' in its name while this feature will make the connection first and foremost 'local'.
A dependency will also be necessary to provide management of a serial port.
Because your project is based on a container, you will need to be able to map a serial port to this container.

Last point, as long as the communication with all the central units has not been validated, I will recommend that you do not assign a version 1.XX to your project but to stay on a version 0.XX because to this day I have not had feedback concluding that with LightSys and I absolutely cannot guarantee that communication will work with all types of power plants that theory suggests.

**Comment by vanackej** [comment]
> @vanackej first of all, good job
> 
> I have 2 small remarks:
> 
> * "Update internal state on Partitions before emitting events": you update the state of partitions and zones, I think we should also add for the outputs and the system to be more consistent.

Yes you are absolutely right. I will do the same for them too.

> * "Graceful disconnection ...": At this stage of the modifications, I do not see the need to add the export for the "RiscoPanel".
>   I think that this last point is related to the automatic detection of the type of plant but that it is not yet required at this stage.

Yes, it was a mistake. It would indeed be required only with automatic panel type detection feature.

> 
> Otherwise in principle, your modifications seem correct to me and go in the right direction of the project.
> 
> I await your return on these points before merging.

OK. I should be able to have a look tomorrow.

**Comment by vanackej** [comment]
@TJForc I fixed all the points we discussed. I also corrected some javascript issues in order to cleanup the code base.

**Comment by TJForc** [comment]
I released version 0.10.4 which contains your changes.
Take a look at the "package.json", it was well worth it.

**Comment by pergolafabio** [comment]
hi @vanackej  , can you describe in the readme of your project how we can use it with home assistant? a guide is verry welcome, especially for HassOS users, we are limited...
We can install a docker in portainer or would be verry usefull if you can port it to an addon so we can add it as an extra custom repository for now

thnx, appreciated!

**Comment by robertboccia** [comment]
I echo this, the reality is this is more than likely the biggest area that this new approach would have the biggest impact, there are many hundreds of users of the risco integration for home assistant who I think would benefit, the best way forward though I think would be to chat to @onfreund as he owns the current repo and has been looking for a way to take it local

**Comment by pergolafabio** [comment]
yeah, but onfreund edition is a python version... its not converted to python yet, so the best approach for now is an add-on ... untill it gets converted to python ... am i right? :-)

**Comment by vanackej** [comment]
@TJForc Thanks for the mention in the contributors, very much appreciated 👍 

@pergolafabio Regarding the HA integration, I think it's a little too early to make it public and documented. I want first to have the [panel type autodetection feature](https://github.com/TJForc/risco-lan-bridge/issues/7), as it will allow for simpler configuration and packaging. 

I also have some issues with my local MQTT broker that does not honor the qos and retain flags => I'm forced to republish the online/offline status more frequently as I wish. 

I want to fix all those points before making the project public, as I can't spend much time making support.

**Comment by pergolafabio** [comment]
Ah ok, no problem... For now we can still use Onfreund edition, it works also

**Comment by OnFreund** [comment]
Thanks @robertboccia for tagging me.

I'm very much looking forward to having local support in PyRisco. Unfortunately, I don't have the capacity to take it from 0 to a 100 at the moment, but I'm happy to both review and contribute PRs as part of a larger effort, if we have other people also supporting this,
If we maintain the same interface in PyRisco (where you can either init a local connection or a cloud connection, but get back an object that behaves the same and abstracts the connection method), there will be minimal changes to the HA integration - mostly just allowing the user to configure the type of connection and relevant parameters. The rest stays mostly the same.

**Pull request merged**
